# git clone https://github.com/mpi-forum/pympistandard
# mkdir data
# cp pympistandard/src/pympistandard/data/apis.json data
#
# julia dev/genapi.jl

using JSON

# Remove line numbers. Line numbers are usually wrong because they
# point to this file, instead of the file where the code originates.
function remove_all_linenums!(ex)
    ex isa Expr || return ex
    if ex.head === :macrocall
        # second arg of macrocall is always a LineNumberNode
        ex.args[2] = nothing
    end
    filter!(a -> !(a isa LineNumberNode), ex.args)
    foreach(remove_all_linenums!, ex.args)
    return ex
end

struct MPI_Info end

function kind2ccalltype(kind)
    return Dict("ERROR_CODE" => Cint, "INFO" => MPI_Info, "LOGICAL" => Bool, "LOGICAL_VOID" => Cvoid, "TYPECLASS_SIZE" => Cint)[kind]
end

function ccalltype2funtype(ccalltype)
    return get(Dict(Cint => Integer), ccalltype, ccalltype)
end

function gen_function(api)
    # Get function description
    attributes = api["attributes"]
    name = api["name"]
    parameters = api["parameters"]
    return_kind = api["return_kind"]

    println(api["name"])

    # Ignore some functions
    !attributes["c_expressible"] && return nothing
    attributes["callback"] && return nothing # TODO
    attributes["predefined_function"] != nothing && return nothing # TODO

    # Check parameters
    params = []
    for parameter in parameters
        # Ignore some parameters
        occursin("c_parameter", parameter["suppress"]) && continue

        @assert parameter["array_type"] == ""
        @assert !parameter["asynchronous"]
        @assert !parameter["constant"]
        @assert parameter["func_type"] == ""
        @assert !parameter["large_only"]
        @assert parameter["length"] == nothing
        @assert !parameter["optional"]
        @assert parameter["param_direction"] in ["in", "out"]
        @assert parameter["pointer"] == nothing
        @assert parameter["suppress"] == ""

        push!(params, parameter)
    end

    # Create argument lists
    docfunarglist = []
    docfunargdefs = []
    funarglist = []
    ccallarglist = []
    for param in params
        desc = param["desc"]

        kind = param["kind"]
        ccalltype = kind2ccalltype(kind)
        funtype = ccalltype2funtype(ccalltype)

        parname = param["name"]

        param_direction = param["param_direction"]
        if param_direction == "in"
            # do nothing
        elseif param_direction == "out"
            ccalltype = Ref{ccalltype}
            funtype = Ref{ccalltype}
        else
            @assert false
        end

        push!(docfunarglist, "$parname::$funtype")
        push!(docfunargdefs, "`$parname`: $desc")
        push!(funarglist, :($(Symbol(parname))::$funtype))
        push!(ccallarglist, :($(Symbol(parname))::$ccalltype))
    end

    # Return type
    ccall_return_type = kind2ccalltype(return_kind)
    fun_return_type = ccall_return_type

    # Create docstring
    doclines = []
    push!(doclines, "    $name($(join(docfunarglist, ", ")))::$fun_return_type")
    for docfunargdef in docfunargdefs
        push!(doclines, "    - $docfunargdef")
    end
    docstring = join(doclines, "\n")

    code = quote
        @doc $docstring function $(Symbol(name))($(funarglist...))
            return @ccall libmpi.$(Symbol(name))($(ccallarglist...))::$ccall_return_type
        end
    end
    remove_all_linenums!(code)

    return code
end

function main()
    # Read API
    apis = JSON.parsefile("data/apis.json")

    open("gen/api.jl", "w") do file
        println(file, "# MPI API")
        println(file, "# This file is autogenerated")

        count=0
        # Traverse all functions
        for key in sort(collect(keys(apis)))
            api = apis[key]

            code = gen_function(api)
            println(file)
            println(file, code)

            count+=1
            count==10 && break
        end
    end
end

main()
