name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{matrix.config.version}} - ${{matrix.config.os}} - ${{matrix.config.arch}} - ${{matrix.mpi}} - ${{github.event_name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        # See <https://julialang-s3.julialang.org/bin/versions.json> for available Julia versions
        mpi: [MPICH, OpenMPI]
        config:
          - arch: "x64"
            os: "macOS-15-intel"
            version: "1.12"
          - arch: "x64"
            os: "ubuntu-24.04"
            version: "1.12"
          #TODO - arch: "x64"
          #TODO   os: "windows-2025"
          #TODO   version: "1.12"
          #TODO mpi: MicrosoftMPI
          - arch: "arm64"
            os: "macOS-26"
            version: "1.12"
          - arch: "arm64"
            os: "ubuntu-24.04-arm"
            version: "1.12"
          - arch: "x86"
            os: "ubuntu-24.04"
            version: "1.12"
          - arch: "x64"
            os: "ubuntu-24.04"
            version: "^1.13.0-beta1"
          - arch: "x64"
            os: "ubuntu-24.04"
            version: "1.11"
          - arch: "x64"
            os: "ubuntu-24.04"
            version: "1.10"
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{matrix.config.version}}
          arch: ${{matrix.config.arch}}
      - uses: julia-actions/cache@v2
      - name: "Select MPI"
        run: |
          julia --project=@. --eval '
              using Pkg
              Pkg.add("MPIPreferences")
              using MPIPreferences
              MPIPreferences.use_jll_binary("${{matrix.mpi}}_jll")
              if "${{matrix.mpi}}" == "OpenMPI" && sizeof(Ptr) == 4
                  # Use OpenMPI 4 on 32-bit platforms
                  Pkg.add(name="OpenMPI_jll", version="4")
              end
          '
      - uses: julia-actions/julia-buildpkg@v1
      # - uses: julia-actions/julia-runtest@v1
      - name: "Run single-process tests"
        run: |
          julia --project=@. test/runtests.jl
      - name: "Run multi-process tests"
        run: |
          julia --project=@. --eval '
              using MPINext
              MPINext.mpiexec() do mpiexec
                  if "${{matrix.mpi}}" == "OpenMPI"
                      run(`$mpiexec --oversubscribe -n 4 julia --project=@. test/runtests.jl`)
                  else
                      run(`$mpiexec -n 4 julia --project=@. test/runtests.jl`)
                  end
              end
          ' || {
              for i in 0 1 2 3; do
                  echo "*** Log file for MPI process $i"
                  cat MPINext_test.$i.log
              done
              false
          }
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          slug: eschnett/MPINext.jl
